services:
  nest:
    container_name: fullstack_example
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    ports:
      - 4000:4000
    command: npm run start:dev
    networks:
      - fullstack_example_net
    depends_on:
      - redis-master
      - postgres

  postgres:
    container_name: fullstack_example_db
    image: postgres
    env_file: .env
    networks:
      - fullstack_example_net
    volumes:
      - fullstackdbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis-master:
    hostname: redis-master
    container_name: redis-master
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - fullstack_example_net

networks:
  fullstack_example_net:
volumes:
  fullstackdbdata:
